# fly.toml app configuration file generated for shadowberatbot on 2023-09-20T12:34:07+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "shadowberatbot"
primary_region = "ams"

